"""
stats_gen.py — Fortnite player stats lookup + image card generation.

Canvas layout (1500 × 820):
  ┌─────────────────────────────────────────────────────────────────────┐
  │ USERNAME                                      Generated by FNLeak  │
  │ FORTNITE STATS                                                      │
  ├──────────────────┬──────────────────────────────────┬──────────────┤
  │  OVERALL STATS   │  SOLO STATS                      │  OTHER INFO  │
  │  deaths/wr/kd    │  W  M  WR  KD  K  KPM  D         │  BP level/%  │
  │  kpm/kills/match │──────────────────────────────────│  LTM W/M     │
  │                  │  DUO STATS                       │              │
  │  [big wins num]  │  W  M  WR  KD  K  KPM  D         │              │
  │  [win-rate bar]  │──────────────────────────────────│              │
  │                  │  SQUAD STATS                     │              │
  │                  │  W  M  WR  KD  K  KPM  D         │              │
  └──────────────────┴──────────────────────────────────┴──────────────┘
"""
from __future__ import annotations

import os
from typing import Optional

import requests
from PIL import Image, ImageDraw, ImageFont

FORTNITE_API  = "https://fortnite-api.com"   # map / other endpoints
_STATS_API    = "https://fortnite-api.com"      # player stats (API key required)

# ── Canvas constants ──────────────────────────────────────────────────────────
W, H = 1500, 680

# Background gradient
_BG_TOP = (14, 14, 14)
_BG_BOT = (20, 20, 28)

# Text
_WHITE   = (240, 236, 228)   # bone-white
_DIM     = (130, 126, 122)   # muted label
_TEAL    = (55,  195, 175)   # section header accent
_GOLD    = (220, 170,  45)   # wins highlight
_ACCENT  = (140,  65, 220)   # purple bar fill

_PANEL_A = 45                # semi-transparent panel alpha (0-255)


# ── Helpers ───────────────────────────────────────────────────────────────────

def _font(path: Optional[str], size: int) -> ImageFont.FreeTypeFont:
    if path and os.path.exists(path):
        try:
            return ImageFont.truetype(path, size)
        except Exception:
            pass
    return ImageFont.load_default()


def _txt(draw: ImageDraw.Draw, xy, text: str, font, fill, anchor="mm"):
    draw.text(xy, str(text), font=font, fill=fill, anchor=anchor)


def _panel(canvas: Image.Image, x1, y1, x2, y2, r: int = 16, a: int = _PANEL_A):
    """Alpha-composite a semi-transparent rounded-rect panel onto canvas."""
    ov = Image.new("RGBA", canvas.size, (0, 0, 0, 0))
    d  = ImageDraw.Draw(ov)
    d.rounded_rectangle([x1, y1, x2, y2], radius=r, fill=(255, 255, 255, a))
    canvas.alpha_composite(ov)


def _fmt(val, decimals: int = 0, suffix: str = "") -> str:
    if val in (None, "", {}, "—"):
        return "—"
    try:
        v = float(val)
        if decimals == 0:
            return f"{int(round(v)):,}{suffix}"
        return f"{v:.{decimals}f}{suffix}"
    except Exception:
        return str(val)


def _mode(data: dict, mode: str) -> dict:
    try:
        return (data.get("stats") or {}).get("all", {}).get(mode) or {}
    except Exception:
        return {}


# ── Section row painter ───────────────────────────────────────────────────────

_MODE_COLS = [
    ("wins",          "WINS",    0,  ""),
    ("matches",       "MATCHES", 0,  ""),
    ("winRate",       "WIN %",   2,  "%"),
    ("kd",            "K/D",     2,  ""),
    ("kills",         "KILLS",   0,  ""),
    ("killsPerMatch", "KPM",     2,  ""),
    ("deaths",        "DEATHS",  0,  ""),
]


def _draw_mode_row(
    canvas: Image.Image,
    fp: Optional[str],
    title: str,
    stats: dict,
    x1, y1, x2, y2,
):
    _panel(canvas, x1, y1, x2, y2, r=14, a=_PANEL_A)
    draw    = ImageDraw.Draw(canvas)
    f_title = _font(fp, 30)
    f_val   = _font(fp, 34)
    f_lbl   = _font(fp, 18)

    _txt(draw, (x1 + 18, y1 + 28), title, f_title, _TEAL, anchor="lm")

    n      = len(_MODE_COLS)
    col_w  = (x2 - x1) / n
    val_y  = y1 + 72
    lbl_y  = val_y + 36

    for i, (key, label, dec, suf) in enumerate(_MODE_COLS):
        cx = x1 + col_w * (i + 0.5)
        _txt(draw, (cx, val_y), _fmt(stats.get(key), dec, suf), f_val, _WHITE)
        _txt(draw, (cx, lbl_y), label,                           f_lbl, _DIM)


# ── Main generation function ──────────────────────────────────────────────────

def generate_stats_image(data: dict, font_path: Optional[str], out_path: str) -> str:
    """Render a stats card from API data. Saves JPEG, returns out_path."""

    # Background gradient
    canvas = Image.new("RGBA", (W, H))
    draw   = ImageDraw.Draw(canvas)
    for y in range(H):
        t = y / max(H - 1, 1)
        c = tuple(int(_BG_TOP[i] + (_BG_BOT[i] - _BG_TOP[i]) * t) for i in range(3)) + (255,)
        draw.line([(0, y), (W - 1, y)], fill=c)

    # Fonts
    f_user  = _font(font_path, 58)
    f_sub   = _font(font_path, 22)
    f_hdr   = _font(font_path, 32)
    f_big   = _font(font_path, 100)
    f_val   = _font(font_path, 36)
    f_lbl   = _font(font_path, 20)
    f_wm    = _font(font_path, 18)

    # ── Header ────────────────────────────────────────────────────────────────
    username = (data.get("account") or {}).get("name", "Unknown").upper()
    draw = ImageDraw.Draw(canvas)
    _txt(draw, (W // 2, 42),  username,        f_user, _WHITE,  "mm")
    _txt(draw, (W // 2, 80),  "FORTNITE STATS", f_sub,  _DIM,   "mm")
    _txt(draw, (W - 18, 14),  "Generated by FNLeak", f_wm, _DIM, "rt")

    PANEL_Y1, PANEL_Y2 = 100, 660

    # ── Left panel: Overall ───────────────────────────────────────────────────
    LX1, LX2 = 18, 415
    _panel(canvas, LX1, PANEL_Y1, LX2, PANEL_Y2, r=16)
    draw = ImageDraw.Draw(canvas)

    overall = _mode(data, "overall")
    lcx     = (LX1 + LX2) // 2

    _txt(draw, (lcx, PANEL_Y1 + 28), "OVERALL STATS", f_hdr, _TEAL)

    # 2×3 stat grid — tightly packed
    grid_rows = [
        [("deaths",        "DEATHS",  0, ""),
         ("winRate",       "WIN %",   2, "%"),
         ("kd",            "K/D",     2, "")],
        [("killsPerMatch", "KPM",     2, ""),
         ("kills",         "KILLS",   0, ""),
         ("matches",       "MATCHES", 0, "")],
    ]
    col_xs = [LX1 + 72, lcx, LX2 - 72]
    for ri, row in enumerate(grid_rows):
        for ci, (key, label, dec, suf) in enumerate(row):
            cx  = col_xs[ci]
            vy  = PANEL_Y1 + 88 + ri * 90
            ly  = vy + 32
            _txt(draw, (cx, vy), _fmt(overall.get(key), dec, suf), f_val, _WHITE)
            _txt(draw, (cx, ly), label,                             f_lbl, _DIM)

    # Wins — directly below the grid with minimal gap
    wins  = _fmt(overall.get("wins"), 0)
    WIN_Y = PANEL_Y1 + 300
    _txt(draw, (lcx, WIN_Y),       wins,  f_big,  _GOLD)
    _txt(draw, (lcx, WIN_Y + 86),  "WINS", f_hdr, _DIM)

    # Win-rate bar
    try:
        wr_f = float(overall.get("winRate", 0)) / 100
        BAR_Y  = WIN_Y + 124
        BX1, BX2 = LX1 + 28, LX2 - 28
        bar_w  = BX2 - BX1
        ov2    = Image.new("RGBA", canvas.size, (0, 0, 0, 0))
        d2     = ImageDraw.Draw(ov2)
        d2.rounded_rectangle([BX1, BAR_Y, BX2, BAR_Y + 10], radius=5,
                              fill=(60, 60, 60, 180))
        filled = max(4, int(bar_w * min(wr_f, 1.0)))
        d2.rounded_rectangle([BX1, BAR_Y, BX1 + filled, BAR_Y + 10], radius=5,
                              fill=_ACCENT + (200,))
        canvas.alpha_composite(ov2)
        draw = ImageDraw.Draw(canvas)
        _txt(draw, (lcx, BAR_Y + 22),
             _fmt(overall.get("winRate"), 2, "% Win Rate"), f_lbl, _DIM)
    except Exception:
        pass

    # ── Center: Solo / Duo / Squad rows ──────────────────────────────────────
    CX1, CX2 = 438, 1148
    row_h    = (PANEL_Y2 - PANEL_Y1 - 12) // 3
    mode_cfg = [
        ("solo",  "SOLO STATS"),
        ("duo",   "DUO STATS"),
        ("squad", "SQUAD STATS"),
    ]
    for i, (key, title) in enumerate(mode_cfg):
        py1 = PANEL_Y1 + i * (row_h + 6)
        py2 = py1 + row_h
        _draw_mode_row(canvas, font_path, title, _mode(data, key),
                       CX1, py1, CX2, py2)

    # ── Right panel: Battle Pass + LTM ───────────────────────────────────────
    RX1, RX2 = 1172, 1480
    _panel(canvas, RX1, PANEL_Y1, RX2, PANEL_Y2, r=16)
    draw = ImageDraw.Draw(canvas)
    rcx  = (RX1 + RX2) // 2

    _txt(draw, (rcx, PANEL_Y1 + 28), "OTHER INFO", f_hdr, _TEAL)

    # Battle pass
    bp          = data.get("battlePass") or {}
    bp_level    = bp.get("level",    "—")
    bp_progress = bp.get("progress", "—")

    _txt(draw, (rcx,      PANEL_Y1 + 68),   "BATTLE PASS",              f_lbl, _DIM)
    _txt(draw, (RX1 + 78, PANEL_Y1 + 110),  _fmt(bp_level, 0),          f_val, _WHITE)
    _txt(draw, (RX1 + 78, PANEL_Y1 + 140),  "LEVEL",                    f_lbl, _DIM)
    _txt(draw, (RX2 - 78, PANEL_Y1 + 110),  _fmt(bp_progress, 0, "%"),  f_val, _WHITE)
    _txt(draw, (RX2 - 78, PANEL_Y1 + 140),  "PROGRESS",                 f_lbl, _DIM)

    # LTM
    ltm = _mode(data, "ltm")
    _txt(draw, (rcx,      PANEL_Y1 + 196),  "LTM STATS",                f_lbl, _DIM)
    _txt(draw, (RX1 + 78, PANEL_Y1 + 238),  _fmt(ltm.get("wins"),    0), f_val, _WHITE)
    _txt(draw, (RX1 + 78, PANEL_Y1 + 268),  "WINS",                     f_lbl, _DIM)
    _txt(draw, (RX2 - 78, PANEL_Y1 + 238),  _fmt(ltm.get("matches"), 0), f_val, _WHITE)
    _txt(draw, (RX2 - 78, PANEL_Y1 + 268),  "MATCHES",                  f_lbl, _DIM)
    _txt(draw, (RX1 + 78, PANEL_Y1 + 318),  _fmt(ltm.get("kills"),   0), f_val, _WHITE)
    _txt(draw, (RX1 + 78, PANEL_Y1 + 348),  "KILLS",                    f_lbl, _DIM)
    _txt(draw, (RX2 - 78, PANEL_Y1 + 318),  _fmt(ltm.get("kd"),   2),   f_val, _WHITE)
    _txt(draw, (RX2 - 78, PANEL_Y1 + 348),  "K/D",                      f_lbl, _DIM)

    # Save
    os.makedirs(os.path.dirname(out_path) if os.path.dirname(out_path) else ".", exist_ok=True)
    canvas.convert("RGB").save(out_path, "JPEG", quality=95, optimize=True)
    return out_path


# ── Public API ────────────────────────────────────────────────────────────────

def _normalize(data: dict) -> dict:
    """Map fortnite-api.com stats response → shape generate_stats_image expects."""
    account = data.get("account") or {}
    bp      = data.get("battlePass") or {}
    stats   = (data.get("stats") or {}).get("all") or {}

    def _mode(src: dict) -> dict:
        return {
            "wins":          src.get("wins", 0),
            "kills":         src.get("kills", 0),
            "kd":            src.get("kd", 0.0),
            "winRate":       src.get("winRate", 0.0),
            "matches":       src.get("matches", 0),
            "minutesPlayed": src.get("minutesPlayed", 0),
            "deaths":        src.get("deaths", 0),
        }

    return {
        "account":    {"name": account.get("name", ""), "id": account.get("id", "")},
        "battlePass": {"level": bp.get("level", 0), "progress": bp.get("progress", 0)},
        "stats": {
            "all": {
                "overall": _mode(stats.get("overall") or {}),
                "solo":    _mode(stats.get("solo")    or {}),
                "duo":     _mode(stats.get("duo")     or {}),
                "squad":   _mode(stats.get("squad")   or {}),
                "ltm":     _mode(stats.get("ltm")     or {}),
            }
        },
        "meta": data.get("meta", {}),
    }


def fetch_stats(username: str, account_type: str = "epic",
                api_key: Optional[str] = None) -> dict:
    """
    Fetch lifetime BR stats via fortnite-api.com — API key required.
    Raises ValueError with a readable message on failure.
    """
    if not api_key:
        raise ValueError(
            "No API key configured.\n"
            "Get a free key at dash.fortnite-api.com and add it in Settings."
        )

    r = requests.get(
        f"{_STATS_API}/v2/stats/br/v2",
        params={"name": username, "accountType": account_type, "timeWindow": "lifetime"},
        headers={"Authorization": api_key},
        timeout=15,
    )

    if r.status_code == 403:
        try:
            body     = r.json()
            err_msg  = (body.get("error") or "").lower()
            raw_msg  = body.get("error") or body.get("message") or ""
        except Exception:
            err_msg = ""
            raw_msg = ""
        if "private" in err_msg or "disabled" in err_msg:
            raise ValueError(
                f"'{username}' has their stats set to private.\n"
                "They need to enable public stats in Epic account settings."
            )
        detail = f"\n(API said: {raw_msg})" if raw_msg else ""
        raise ValueError(f"Invalid or missing API key. Check your key in Settings → Player Stats.{detail}")
    if r.status_code == 404:
        raise ValueError(f"Player '{username}' not found.")

    r.raise_for_status()
    data = r.json().get("data") or {}

    if not data.get("stats"):
        raise ValueError(
            "No stats found — player may have private stats or has never played BR."
        )

    return _normalize(data)


def fetch_and_generate(
    username: str,
    account_type: str = "epic",
    font_path: Optional[str] = None,
    out_dir: str = "icons",
    api_key: Optional[str] = None,
) -> tuple[dict, str]:
    """Fetch stats + generate image. Returns (data, image_path)."""
    data     = fetch_stats(username, account_type, api_key=api_key)
    safe     = "".join(c if c.isalnum() else "_" for c in username)
    out_path = os.path.join(out_dir, f"stats_{safe}.jpg")
    generate_stats_image(data, font_path, out_path)
    return data, out_path
